services:
  ebook-metadata-updater:
    build: .
    volumes:
      - .:/ebooks
    environment:
      PYTHONUNBUFFERED: "1"
      DIRECTORY: "/ebooks"
      TEMPLATE: "{author} {type} {year} - Ausgabe {ausgabe} ({date_year}-{date_month}-{date_day})"
      TITLE: "{ausgabe}/{year[-2:]}"
      DESCRIPTION: "{author} {type} {ausgabe}/{year[-2:]}"
      SUBJECT: "{author} {type}"
      LOG_AVAILABLE: false